insert into Users (id, email, password, is_active) values (1, 'mbissill0@techcrunch.com', 'Matthew Spain Airport', false);
insert into Users (id, email, password, is_active) values (2, 'iohearn1@aol.com', 'Kananga Airport', true);
insert into Users (id, email, password, is_active) values (3, 'tvanderbrugge2@merriam-webster.com', 'El Nido Airport', false);
insert into Users (id, email, password, is_active) values (4, 'cadamiec3@usatoday.com', 'Mamai Airport', false);
insert into Users (id, email, password, is_active) values (5, 'kverrico4@google.fr', 'Jabalpur Airport', true);
insert into Users (id, email, password, is_active) values (6, 'mjerram5@indiegogo.com', 'Jacksonville Naval Air Station (Towers Field)', false);
insert into Users (id, email, password, is_active) values (7, 'asent6@51.la', 'Lusanga Airport', false);
insert into Users (id, email, password, is_active) values (8, 'mchristophle7@google.ca', 'Laguindingan Airport', false);
insert into Users (id, email, password, is_active) values (9, 'fbickerdyke8@time.com', 'Hazleton Municipal Airport', true);
insert into Users (id, email, password, is_active) values (10, 'jabsolon9@globo.com', 'Venice Municipal Airport', true);
insert into Users (id, email, password, is_active) values (11, 'kpeyntuea@wunderground.com', 'Lethem Airport', true);
insert into Users (id, email, password, is_active) values (12, 'dmccartanb@dmoz.org', 'Eskilstuna Airport', false);
insert into Users (id, email, password, is_active) values (13, 'asummerbellc@delicious.com', 'Presidente José Sarney Airport', true);
insert into Users (id, email, password, is_active) values (14, 'daugustined@netvibes.com', 'Ituberá Airport', false);
insert into Users (id, email, password, is_active) values (15, 'rderricoate@answers.com', 'Ricardo García Posada Airport', true);
insert into Users (id, email, password, is_active) values (16, 'pwhissellf@tripod.com', 'Scusciuban Airport', true);
insert into Users (id, email, password, is_active) values (17, 'bstaintong@ftc.gov', 'Teterboro Airport', false);
insert into Users (id, email, password, is_active) values (18, 'sjahnh@purevolume.com', 'Plastun Airport', true);
insert into Users (id, email, password, is_active) values (19, 'bliccardii@nih.gov', 'Baniyala Airport', true);
insert into Users (id, email, password, is_active) values (20, 'hportej@wikipedia.org', 'Etadunna Airport', true);
insert into Users (id, email, password, is_active) values (21, 'jreginak@reuters.com', 'Jorhat Airport', true);
insert into Users (id, email, password, is_active) values (22, 'bzienkiewiczl@go.com', 'Girua Airport', false);
insert into Users (id, email, password, is_active) values (23, 'talldism@umich.edu', 'Ontario Municipal Airport', true);
insert into Users (id, email, password, is_active) values (24, 'mlegonn@symantec.com', 'Statesville Regional Airport', false);
insert into Users (id, email, password, is_active) values (25, 'dwaileso@privacy.gov.au', 'Can Tho International Airport', true);
insert into Users (id, email, password, is_active) values (26, 'snewvillp@sphinn.com', 'Kogalym International Airport', false);
insert into Users (id, email, password, is_active) values (27, 'cbuntineq@cdbaby.com', 'Akutan Seaplane Base', true);
insert into Users (id, email, password, is_active) values (28, 'bnapoleoner@weebly.com', 'Lengbati Airport', false);
insert into Users (id, email, password, is_active) values (29, 'laubins@tinypic.com', 'Playón Chico Airport', false);
insert into Users (id, email, password, is_active) values (30, 'lcristoforettit@time.com', 'Nikolayevsk-na-Amure Airport', true);
insert into Users (id, email, password, is_active) values (31, 'wuzzellu@arstechnica.com', 'Bella Coola Airport', false);
insert into Users (id, email, password, is_active) values (32, 'sgoodanewv@cpanel.net', 'EMBRAER - Unidade Gavião Peixoto Airport', false);
insert into Users (id, email, password, is_active) values (33, 'ccrousew@skyrock.com', 'Wunnumin Lake Airport', true);
insert into Users (id, email, password, is_active) values (34, 'jdulsonx@state.tx.us', 'Wells Municipal Airport/Harriet Field', false);
insert into Users (id, email, password, is_active) values (35, 'fkerrichy@unicef.org', 'Guajará-Mirim Airport', false);
insert into Users (id, email, password, is_active) values (36, 'kblasiz@myspace.com', 'Asahikawa Airport', false);
insert into Users (id, email, password, is_active) values (37, 'chartfield10@oaic.gov.au', 'La Araucanía Airport', true);
insert into Users (id, email, password, is_active) values (38, 'kgelland11@cbsnews.com', 'Dinangat Airport', true);
insert into Users (id, email, password, is_active) values (39, 'mmacaughtrie12@sourceforge.net', 'Southwest Georgia Regional Airport', true);
insert into Users (id, email, password, is_active) values (40, 'tstoak13@arizona.edu', 'Oakdale Airport', true);
insert into Users (id, email, password, is_active) values (41, 'ibilles14@oakley.com', 'Centennial Airport', false);
insert into Users (id, email, password, is_active) values (42, 'nbiaggioli15@nih.gov', 'Berens River Airport', false);
insert into Users (id, email, password, is_active) values (43, 'alawrenz16@nytimes.com', 'Ingeniero Alberto Acuña Ongay International Airport', true);
insert into Users (id, email, password, is_active) values (44, 'rlyal17@rambler.ru', 'Garaina Airport', true);
insert into Users (id, email, password, is_active) values (45, 'hambrozewicz18@dagondesign.com', 'Clinton Creek Airport', false);
insert into Users (id, email, password, is_active) values (46, 'rjorg19@t-online.de', 'Suzhou Guangfu Airport', false);
insert into Users (id, email, password, is_active) values (47, 'mloukes1a@vk.com', 'Daegu Airport', false);
insert into Users (id, email, password, is_active) values (48, 'mbaldock1b@bandcamp.com', 'Alberto Lleras Camargo Airport', false);
insert into Users (id, email, password, is_active) values (49, 'alyttle1c@booking.com', 'Banaina Airport', true);
insert into Users (id, email, password, is_active) values (50, 'scapstack1d@cdbaby.com', 'Guari Airport', false);